//! R12.1 — Lisp bridge for ML primitive catalog.
//!
//! Lifts `MlPrimitive` and `PrimitiveCensus` into tatara-lisp Sexp
//! forms. Same pattern as `policy_lisp.rs` (R10.1) and
//! `mechanism::to_sexp` (M1). Every detectable structural property
//! has a canonical Lisp representation:
//!
//! ```text
//!   (primitive :kind left-identity :op add :identity 0)
//!   (primitive :kind right-identity :op mul :identity 1)
//!   (primitive :kind involution :f neg)
//!   (primitive :kind idempotence :f relu)
//!   (primitive :kind left-distributive :outer mul :inner add)
//!   (primitive :kind right-distributive :outer mul :inner add)
//!   (primitive :kind homomorphism :f succ :op add)
//!   (primitive :kind meta-distributive)
//! ```
//!
//! A `PrimitiveCensus` — the per-library aggregate — becomes:
//!
//! ```text
//!   (census
//!     :total-rules        N
//!     :left-identity      c1
//!     :right-identity     c2
//!     :involution         c3
//!     :idempotence        c4
//!     :left-distributive  c5
//!     :right-distributive c6
//!     :homomorphism       c7
//!     :meta-distributive  c8)
//! ```
//!
//! Why a Lisp form: once the catalog is data, the catalog can be
//! EDITED and REGENERATED by Lisp programs. A user or the machine
//! itself can add new primitive entries to the catalog without
//! touching Rust. Today the detectors are still Rust, but the
//! reported findings are fully Lisp-structured — the boundary
//! moves toward fluid-Lisp one step at a time.

use mathscape_core::primitives::{IdentityForm, MlPrimitive, PrimitiveCensus};
use tatara_lisp::ast::{Atom, Sexp};

/// Convert an `MlPrimitive` to its canonical Sexp form.
#[must_use]
pub fn primitive_to_sexp(p: &MlPrimitive) -> Sexp {
    let mut items: Vec<Sexp> = vec![Sexp::symbol("primitive"), Sexp::keyword("kind")];
    match p {
        MlPrimitive::LeftIdentity { op, identity } => {
            items.push(Sexp::symbol("left-identity"));
            items.push(Sexp::keyword("op"));
            items.push(Sexp::int(*op as i64));
            items.push(Sexp::keyword("identity"));
            items.push(identity_to_sexp(identity));
        }
        MlPrimitive::RightIdentity { op, identity } => {
            items.push(Sexp::symbol("right-identity"));
            items.push(Sexp::keyword("op"));
            items.push(Sexp::int(*op as i64));
            items.push(Sexp::keyword("identity"));
            items.push(identity_to_sexp(identity));
        }
        MlPrimitive::Involution { f } => {
            items.push(Sexp::symbol("involution"));
            items.push(Sexp::keyword("f"));
            items.push(Sexp::int(*f as i64));
        }
        MlPrimitive::Idempotence { f } => {
            items.push(Sexp::symbol("idempotence"));
            items.push(Sexp::keyword("f"));
            items.push(Sexp::int(*f as i64));
        }
        MlPrimitive::LeftDistributive { outer, inner } => {
            items.push(Sexp::symbol("left-distributive"));
            items.push(Sexp::keyword("outer"));
            items.push(Sexp::int(*outer as i64));
            items.push(Sexp::keyword("inner"));
            items.push(Sexp::int(*inner as i64));
        }
        MlPrimitive::RightDistributive { outer, inner } => {
            items.push(Sexp::symbol("right-distributive"));
            items.push(Sexp::keyword("outer"));
            items.push(Sexp::int(*outer as i64));
            items.push(Sexp::keyword("inner"));
            items.push(Sexp::int(*inner as i64));
        }
        MlPrimitive::Homomorphism { f, op } => {
            items.push(Sexp::symbol("homomorphism"));
            items.push(Sexp::keyword("f"));
            items.push(Sexp::int(*f as i64));
            items.push(Sexp::keyword("op"));
            items.push(Sexp::int(*op as i64));
        }
        MlPrimitive::MetaDistributive => {
            items.push(Sexp::symbol("meta-distributive"));
        }
        MlPrimitive::MetaIdentity => {
            items.push(Sexp::symbol("meta-identity"));
        }
    }
    Sexp::List(items)
}

fn identity_to_sexp(id: &IdentityForm) -> Sexp {
    match id {
        IdentityForm::Nat(n) => Sexp::int(*n as i64),
        // Int identity serialized with an 'i' tag wrapped in a
        // list to disambiguate from Nat. `(int -5)` vs just `-5`
        // (which would be Nat-shaped). Readers match on the
        // wrapping list.
        IdentityForm::Int(n) => Sexp::List(vec![Sexp::symbol("int"), Sexp::int(*n)]),
        IdentityForm::Abstract(v) => {
            Sexp::List(vec![Sexp::symbol("abstract"), Sexp::int(*v as i64)])
        }
    }
}

/// Parse an `MlPrimitive` from Sexp form. `None` if malformed.
#[must_use]
pub fn primitive_from_sexp(sexp: &Sexp) -> Option<MlPrimitive> {
    let items = match sexp {
        Sexp::List(items) if items.len() >= 3 => items,
        _ => return None,
    };
    match &items[0] {
        Sexp::Atom(Atom::Symbol(s)) if s == "primitive" => {}
        _ => return None,
    }
    match &items[1] {
        Sexp::Atom(Atom::Keyword(k)) if k == "kind" => {}
        _ => return None,
    }
    let kind = match &items[2] {
        Sexp::Atom(Atom::Symbol(s)) => s,
        _ => return None,
    };
    let fields = parse_fields(&items[3..])?;

    match kind.as_str() {
        "left-identity" => Some(MlPrimitive::LeftIdentity {
            op: fields.get_int("op")? as u32,
            identity: fields.get_identity("identity")?,
        }),
        "right-identity" => Some(MlPrimitive::RightIdentity {
            op: fields.get_int("op")? as u32,
            identity: fields.get_identity("identity")?,
        }),
        "involution" => Some(MlPrimitive::Involution {
            f: fields.get_int("f")? as u32,
        }),
        "idempotence" => Some(MlPrimitive::Idempotence {
            f: fields.get_int("f")? as u32,
        }),
        "left-distributive" => Some(MlPrimitive::LeftDistributive {
            outer: fields.get_int("outer")? as u32,
            inner: fields.get_int("inner")? as u32,
        }),
        "right-distributive" => Some(MlPrimitive::RightDistributive {
            outer: fields.get_int("outer")? as u32,
            inner: fields.get_int("inner")? as u32,
        }),
        "homomorphism" => Some(MlPrimitive::Homomorphism {
            f: fields.get_int("f")? as u32,
            op: fields.get_int("op")? as u32,
        }),
        "meta-distributive" => Some(MlPrimitive::MetaDistributive),
        "meta-identity" => Some(MlPrimitive::MetaIdentity),
        _ => None,
    }
}

struct Fields<'a> {
    pairs: Vec<(String, &'a Sexp)>,
}

impl<'a> Fields<'a> {
    fn get(&self, key: &str) -> Option<&'a Sexp> {
        self.pairs
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| *v)
    }

    fn get_int(&self, key: &str) -> Option<i64> {
        match self.get(key)? {
            Sexp::Atom(Atom::Int(n)) => Some(*n),
            _ => None,
        }
    }

    fn get_identity(&self, key: &str) -> Option<IdentityForm> {
        let sexp = self.get(key)?;
        match sexp {
            Sexp::Atom(Atom::Int(n)) => Some(IdentityForm::Nat(*n as u64)),
            Sexp::List(items) if items.len() == 2 => {
                let tag = match &items[0] {
                    Sexp::Atom(Atom::Symbol(s)) => s,
                    _ => return None,
                };
                let v = match &items[1] {
                    Sexp::Atom(Atom::Int(n)) => *n,
                    _ => return None,
                };
                match tag.as_str() {
                    "int" => Some(IdentityForm::Int(v)),
                    "abstract" => Some(IdentityForm::Abstract(v as u32)),
                    _ => None,
                }
            }
            _ => None,
        }
    }
}

fn parse_fields(items: &[Sexp]) -> Option<Fields<'_>> {
    if items.len() % 2 != 0 {
        return None;
    }
    let mut pairs = Vec::new();
    let mut i = 0;
    while i + 1 < items.len() {
        let key = match &items[i] {
            Sexp::Atom(Atom::Keyword(k)) => k.clone(),
            _ => return None,
        };
        pairs.push((key, &items[i + 1]));
        i += 2;
    }
    Some(Fields { pairs })
}

/// Convert a `PrimitiveCensus` to Sexp form.
#[must_use]
pub fn census_to_sexp(c: &PrimitiveCensus) -> Sexp {
    Sexp::List(vec![
        Sexp::symbol("census"),
        Sexp::keyword("total-rules"),
        Sexp::int(c.total_rules as i64),
        Sexp::keyword("left-identity"),
        Sexp::int(c.left_identity as i64),
        Sexp::keyword("right-identity"),
        Sexp::int(c.right_identity as i64),
        Sexp::keyword("involution"),
        Sexp::int(c.involution as i64),
        Sexp::keyword("idempotence"),
        Sexp::int(c.idempotence as i64),
        Sexp::keyword("left-distributive"),
        Sexp::int(c.left_distributive as i64),
        Sexp::keyword("right-distributive"),
        Sexp::int(c.right_distributive as i64),
        Sexp::keyword("homomorphism"),
        Sexp::int(c.homomorphism as i64),
        Sexp::keyword("meta-distributive"),
        Sexp::int(c.meta_distributive as i64),
        Sexp::keyword("meta-identity"),
        Sexp::int(c.meta_identity as i64),
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn left_identity_roundtrips() {
        let p = MlPrimitive::LeftIdentity {
            op: 2,
            identity: IdentityForm::Nat(0),
        };
        let sexp = primitive_to_sexp(&p);
        let back = primitive_from_sexp(&sexp).unwrap();
        assert_eq!(p, back);
    }

    #[test]
    fn right_identity_with_int_identity_roundtrips() {
        let p = MlPrimitive::RightIdentity {
            op: 12,
            identity: IdentityForm::Int(-7),
        };
        let sexp = primitive_to_sexp(&p);
        let back = primitive_from_sexp(&sexp).unwrap();
        assert_eq!(p, back);
    }

    #[test]
    fn abstract_identity_roundtrips() {
        let p = MlPrimitive::LeftIdentity {
            op: 2,
            identity: IdentityForm::Abstract(200),
        };
        let sexp = primitive_to_sexp(&p);
        let back = primitive_from_sexp(&sexp).unwrap();
        assert_eq!(p, back);
    }

    #[test]
    fn involution_roundtrips() {
        let p = MlPrimitive::Involution { f: 14 };
        assert_eq!(
            primitive_from_sexp(&primitive_to_sexp(&p)).unwrap(),
            p
        );
    }

    #[test]
    fn idempotence_roundtrips() {
        let p = MlPrimitive::Idempotence { f: 1 };
        assert_eq!(
            primitive_from_sexp(&primitive_to_sexp(&p)).unwrap(),
            p
        );
    }

    #[test]
    fn distributive_variants_roundtrip() {
        let left = MlPrimitive::LeftDistributive { outer: 3, inner: 2 };
        let right = MlPrimitive::RightDistributive { outer: 3, inner: 2 };
        assert_eq!(
            primitive_from_sexp(&primitive_to_sexp(&left)).unwrap(),
            left
        );
        assert_eq!(
            primitive_from_sexp(&primitive_to_sexp(&right)).unwrap(),
            right
        );
    }

    #[test]
    fn homomorphism_roundtrips() {
        let p = MlPrimitive::Homomorphism { f: 1, op: 2 };
        assert_eq!(
            primitive_from_sexp(&primitive_to_sexp(&p)).unwrap(),
            p
        );
    }

    #[test]
    fn meta_distributive_roundtrips() {
        let p = MlPrimitive::MetaDistributive;
        assert_eq!(
            primitive_from_sexp(&primitive_to_sexp(&p)).unwrap(),
            p
        );
    }

    #[test]
    fn malformed_sexp_returns_none() {
        assert!(primitive_from_sexp(&Sexp::int(42)).is_none());
        assert!(primitive_from_sexp(&Sexp::List(vec![])).is_none());
        assert!(primitive_from_sexp(&Sexp::List(vec![
            Sexp::symbol("wrong-head"),
            Sexp::keyword("kind"),
            Sexp::symbol("involution"),
            Sexp::keyword("f"),
            Sexp::int(1),
        ]))
        .is_none());
    }

    #[test]
    fn census_sexp_form_preserves_all_fields() {
        let c = PrimitiveCensus {
            total_rules: 42,
            left_identity: 1,
            right_identity: 2,
            involution: 3,
            idempotence: 4,
            left_distributive: 5,
            right_distributive: 6,
            homomorphism: 7,
            meta_distributive: 8,
            meta_identity: 9,
        };
        let sexp = census_to_sexp(&c);
        // Confirm all the fields are present by counting
        // (symbol + 10 pairs) = 21 items.
        match sexp {
            Sexp::List(items) => {
                assert_eq!(items.len(), 21);
                // Header is 'census'.
                match &items[0] {
                    Sexp::Atom(Atom::Symbol(s)) => assert_eq!(s, "census"),
                    _ => panic!("expected census header"),
                }
            }
            _ => panic!("expected List"),
        }
    }
}
